debug for crash
enter uImage-name: 7.0.0-mt7622-r64.itb
kernelinput=7.0.0-mt7622-r64.itb
Using ethernet@1b100000 device
TFTP from server 192.168.0.11; our IP address is 192.168.0.19
Filename '7.0.0-mt7622-r64.itb'.
ERROR: reserving fdt memory region failed (addr=0 size=43000000 flags=4)
Load address: 0x44000000
Loading: #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         ###############################################################
         3.1 MiB/s
done
Bytes transferred = 6641284 (655684 hex)
   Using 'conf-1' configuration
   Trying 'kernel-1' kernel subimage
     Description:  Linux Kernel 7.0.0-mt7622
     Type:         Kernel Image
     Compression:  gzip compressed
     Data Start:   0x440000e8
     Data Size:    6607656 Bytes = 6.3 MiB
     Architecture: AArch64
     OS:           Linux
     Load Address: 0x40080000
     Entry Point:  0x40080000
     Hash algo:    sha1
     Hash value:   e0d1feb7a826a57040807cc1dadf4599268f0c74
   Verifying Hash Integrity ... sha1+ OK
   Using 'conf-1' configuration
   Trying 'fdt-1' fdt subimage
     Description:  Flattened Device Tree blob
     Type:         Flat Device Tree
     Compression:  uncompressed
     Data Start:   0x4464d508
     Data Size:    32421 Bytes = 31.7 KiB
     Architecture: AArch64
     Hash algo:    sha1
     Hash value:   f461aba47b76e6ab49689bba3d3b3be81a47dc99
   Verifying Hash Integrity ... sha1+ OK
   Booting using the fdt blob at 0x4464d508
Working FDT set to 4464d508
   Uncompressing Kernel Image
   Loading Device Tree to 000000007e7c4000, end 000000007e7ceea4 ... OK
Working FDT set to 7e7c4000

Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd034]
[    0.000000] Linux version 7.0.0-bpi-r64-mt7622 (frank@frank-u24) (aarch64-linux-gnu-gcc (Ubuntu 13.6
[    0.000000] Machine model: Bananapi BPI-R64
[    0.000000] [Firmware Bug]: Kernel image misaligned at boot, please fix your bootloader!
[    0.000000] OF: reserved mem: 0x0000000042ff0000..0x0000000042ffffff (64 KiB) map non-reusable ramo0
[    0.000000] OF: reserved mem: 0x0000000043000000..0x000000004302ffff (192 KiB) nomap non-reusable s0
[    0.000000] psci: probing for conduit method from DT.
[    0.000000] psci: PSCIv1.1 detected in firmware.
[    0.000000] psci: Using standard PSCI v0.2 function IDs
[    0.000000] psci: MIGRATE_INFO_TYPE not supported.
[    0.000000] psci: SMC Calling Convention v1.4
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000040000000-0x000000007fffffff]
[    0.000000]   DMA32    empty
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000040000000-0x0000000042ffffff]
[    0.000000]   node   0: [mem 0x0000000043000000-0x000000004302ffff]
[    0.000000]   node   0: [mem 0x0000000043030000-0x000000007fffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000040000000-0x000000007fffffff]
[    0.000000] percpu: Embedded 20 pages/cpu s44312 r8192 d29416 u81920
[    0.000000] pcpu-alloc: s44312 r8192 d29416 u81920 alloc=20*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1
[    0.000000] Detected VIPT I-cache on CPU0
[    0.000000] CPU features: detected: ARM erratum 843419
[    0.000000] CPU features: detected: ARM erratum 845719
[    0.000000] alternatives: applying boot alternatives
[    0.000000] Kernel command line: board=bpi-r64 console=ttyS0,115200n1 earlyprintk root=/dev/mmcblk12
[    0.000000] Unknown kernel command line parameters "earlyprintk board=bpi-r64 service=linux", will .
[    0.000000] printk: log buffer data + meta data: 131072 + 458752 = 589824 bytes
[    0.000000] Dentry cache hash table entries: 131072 (order: 8, 1048576 bytes, linear)
[    0.000000] Inode-cache hash table entries: 65536 (order: 7, 524288 bytes, linear)
[    0.000000] software IO TLB: area num 2.
[    0.000000] software IO TLB: mapped [mem 0x000000007eb00000-0x000000007ec00000] (1MB)
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 262144
[    0.000000] mem auto-init: stack:all(zero), heap alloc:off, heap free:off
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=2, Nodes=1
[    0.000000] rcu: Preemptible hierarchical RCU implementation.
[    0.000000] rcu:     RCU event tracing is enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] GIC: GICv2 detected, but range too small and irqchip.gicv2_force_probe not set
[    0.000000] Root IRQ handler: gic_handle_irq
[    0.000000] rcu: srcu_init: Setting srcu_struct sizes based on contention.
[    0.000000] arch_timer: cp15 timer running at 12.50MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x2e2049cda, max_idles
[    0.000000] sched_clock: 56 bits at 13MHz, resolution 80ns, wraps every 4398046511080ns
[    0.000427] Console: colour dummy device 80x25
[    0.000471] Calibrating delay loop (skipped), value calculated using timer frequency.. 25.00 BogoMI)
[    0.000482] pid_max: default: 32768 minimum: 301
[    0.000727] Mount-cache hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.000741] Mountpoint-cache hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.001085] VFS: Finished mounting rootfs on nullfs
[    0.003124] rcu: Hierarchical SRCU implementation.
[    0.003137] rcu:     Max phase no-delay instances is 1000.
[    0.003383] Timer migration: 1 hierarchy levels; 8 children per group; 1 crossnode level
[    0.004068] smp: Bringing up secondary CPUs ...
[    0.004662] Detected VIPT I-cache on CPU1
[    0.004675] CPU features: SANITY CHECK: Unexpected variation in SYS_CNTFRQ_EL0. Boot CPU: 0x00000000
[    0.004715] CPU features: Unsupported CPU feature variation detected.
[    0.004821] CPU1: Booted secondary processor 0x0000000001 [0x410fd034]
[    0.004969] smp: Brought up 1 node, 2 CPUs
[    0.004976] SMP: Total of 2 processors activated.
[    0.004980] CPU: All CPU(s) started at EL2
[    0.004984] CPU features: detected: 32-bit EL0 Support
[    0.004989] CPU features: detected: CRC32 instructions
[    0.005002] CPU features: detected: PMUv3
[    0.005039] alternatives: applying system-wide alternatives
[    0.005563] Memory: 1005348K/1048576K available (8960K kernel code, 1406K rwdata, 4296K rodata, 339)
[    0.006377] devtmpfs: initialized
[    0.013214] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 76450417851s
[    0.013250] posixtimers hash table entries: 1024 (order: 2, 16384 bytes, linear)
[    0.013289] futex hash table entries: 512 (32768 bytes on 1 NUMA nodes, total 32 KiB, linear).
[    0.013344] 28128 pages in range for non-PLT usage
[    0.013348] 519648 pages in range for PLT usage
[    0.014744] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.015334] DMA: preallocated 128 KiB GFP_KERNEL|GFP_DMA pool for atomic allocations
[    0.015392] audit: initializing netlink subsys (disabled)
[    0.015625] audit: type=2000 audit(0.000:1): state=initialized audit_enabled=0 res=1
[    0.016343] i2c-core: driver [dummy] registered
[    0.016372] thermal_sys: Registered thermal governor 'fair_share'
[    0.016377] thermal_sys: Registered thermal governor 'bang_bang'
[    0.016381] thermal_sys: Registered thermal governor 'step_wise'
[    0.016385] thermal_sys: Registered thermal governor 'user_space'
[    0.016460] cpuidle: using governor menu
[    0.016704] hw-breakpoint: found 6 breakpoint and 4 watchpoint registers.
[    0.016774] ASID allocator initialised with 65536 entries
[    0.017936] printk: legacy console [ramoops-1] enabled
[    0.018470] pstore: Registered ramoops as persistent store backend
[    0.018485] ramoops: using 0x10000@0x42ff0000, ecc: 0
[    0.034097] /pcie@1a143000: Fixed dependency cycle(s) with /pcie@1a143000/interrupt-controller
[    0.034573] /pcie@1a145000: Fixed dependency cycle(s) with /pcie@1a145000/interrupt-controller
[    0.039760] SCSI subsystem initialized
[    0.040473] libata version 3.00 loaded.
[    0.040696] usbcore: registered new interface driver usbfs
[    0.040759] usbcore: registered new interface driver hub
[    0.040809] usbcore: registered new device driver usb
[    0.040905] pps_core: LinuxPPS API ver. 1 registered
[    0.040915] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.040989] PTP clock support registered
[    0.042985] vgaarb: loaded
[    0.043501] clocksource: Switched to clocksource arch_sys_counter
[    0.051791] NET: Registered PF_INET protocol family
[    0.052010] IP idents hash table entries: 16384 (order: 5, 131072 bytes, linear)
[    0.053168] tcp_listen_portaddr_hash hash table entries: 512 (order: 1, 8192 bytes, linear)
[    0.053202] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.053221] TCP established hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    0.053285] TCP bind hash table entries: 8192 (order: 6, 262144 bytes, linear)
[    0.053504] TCP: Hash tables configured (established 8192 bind 8192)
[    0.053644] UDP hash table entries: 512 (order: 3, 32768 bytes, linear)
[    0.053866] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    0.054492] RPC: Registered named UNIX socket transport module.
[    0.054523] RPC: Registered udp transport module.
[    0.054532] RPC: Registered tcp transport module.
[    0.054540] RPC: Registered tcp-with-tls transport module.
[    0.054549] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.054568] PCI: CLS 0 bytes, default 64
[    0.055766] Initialise system trusted keyrings
[    0.056036] workingset: timestamp_bits=46 max_order=18 bucket_order=0
[    0.056891] NFS: Registering the id_resolver key type
[    0.056952] Key type id_resolver registered
[    0.056962] Key type id_legacy registered
[    0.056992] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    0.057004] nfs4flexfilelayout_init: NFSv4 Flexfile Layout Driver Registering...
[    0.103825] Key type asymmetric registered
[    0.103855] Asymmetric key parser 'x509' registered
[    0.103923] io scheduler mq-deadline registered
[    0.103936] io scheduler kyber registered
[    0.103989] io scheduler bfq registered
[    0.106541] ledtrig-cpu: registered to indicate activity on CPUs
[    0.123905] mt-pmic-pwrap 10001000.pwrap: unexpected interrupt int=0x1
[    0.125997] mtk-socinfo mtk-socinfo.0.auto: error -ENOENT: Failed to get socinfo data
[    0.126030] mtk-socinfo mtk-socinfo.0.auto: probe with driver mtk-socinfo failed with error -2
[    0.143248] Serial: 8250/16550 driver, 3 ports, IRQ sharing disabled
[    0.145707] printk: legacy console [ttyS0] disabled
[    0.166231] 11002000.serial: ttyS0 at MMIO 0x11002000 (irq = 118, base_baud = 1562500) is a ST166502
[    0.166321] printk: legacy console [ttyS0] enabled
[    1.021634] 1100c000.serial: ttyS1 at MMIO 0x1100c000 (irq = 119, base_baud = 17499995) is a MediaTF
[    1.031607] serial serial0: tty port ttyS1 registered
[    1.037619] mtk_rng 1020f000.rng: registered RNG driver
[    1.037792] random: crng init done
[    1.050598] mtk_soc_eth 1b100000.ethernet: mtk_probe entered
[    1.056342] mtk_soc_eth 1b100000.ethernet: mtk_probe allocated
[    1.062243] mtk_soc_eth 1b100000.ethernet: mtk_probe io remaped
[    1.068187] mtk_soc_eth 1b100000.ethernet: mtk_probe DMA configured
[    1.074464] mtk_soc_eth 1b100000.ethernet: mtk_probe locks initialized
[    1.081014] mtk_soc_eth 1b100000.ethernet: mtk_probe ethsys acquired
[    1.087377] mtk_soc_eth 1b100000.ethernet: mtk_probe infracfg acquired
[    1.094059] mtk_soc_eth 1b100000.ethernet: mtk_probe CCI acquired
[    1.100186] mtk_soc_eth 1b100000.ethernet: mtk_probe pctl acquired
[    1.106377] mtk_soc_eth 1b100000.ethernet: mtk_probe SRAM acquired
[    1.113008] mtk_soc_eth 1b100000.ethernet: mtk_probe offloading initialized
[    1.120023] mtk_soc_eth 1b100000.ethernet: legacy DT: missing interrupt-names.
[    1.127368] mtk_soc_eth 1b100000.ethernet: mtk_probe FE IRQ initialized
[    1.134012] mtk_soc_eth 1b100000.ethernet: mtk_probe PDMA IRQ initialized
[    1.141007] mtk_soc_eth 1b100000.ethernet: mtk_probe clocks acquired
[    1.262640] mtk_soc_eth 1b100000.ethernet: mtk_probe hw initialized
[    1.268974] mtk_soc_eth 1b100000.ethernet: GMAC0 mtk_shared
[    1.274559] mtk_soc_eth 1b100000.ethernet: GMAC0 other_mac:00000000fd26a144
[    1.281532] mtk_soc_eth 1b100000.ethernet: GMAC0 other_mac:00000000fd26a144 pl:000000009ca6a8b9
[    1.290248] Unable to handle kernel NULL pointer dereference at virtual address 0000000000000a00
[    1.299040] Mem abort info:
[    1.301841]   ESR = 0x0000000096000004
[    1.305596]   EC = 0x25: DABT (current EL), IL = 32 bits
[    1.310915]   SET = 0, FnV = 0
[    1.313979]   EA = 0, S1PTW = 0
[    1.317127]   FSC = 0x04: level 0 translation fault
[    1.322011] Data abort info:
[    1.324898]   ISV = 0, ISS = 0x00000004, ISS2 = 0x00000000
[    1.330389]   CM = 0, WnR = 0, TnD = 0, TagAccess = 0
[    1.335447]   GCS = 0, Overlay = 0, DirtyBit = 0, Xs = 0
[    1.340766] [0000000000000a00] user address but active_mm is swapper
[    1.347127] Internal error: Oops: 0000000096000004 [#1]  SMP
[    1.352786] Modules linked in:
[    1.355848] CPU: 0 UID: 0 PID: 1 Comm: swapper/0 Tainted: G S                  7.0.0-bpi-r64-mt7622
[    1.365939] Tainted: [S]=CPU_OUT_OF_SPEC
[    1.369858] Hardware name: Bananapi BPI-R64 (DT)
[    1.374473] pstate: 60000005 (nZCv daif -PAN -UAO -TCO -DIT -SSBS BTYPE=--)
[    1.381436] pc : mtk_add_mac+0x360/0x5a8
[    1.385365] lr : mtk_add_mac+0x360/0x5a8
[    1.389286] sp : ffff80008001bad0
[    1.392597] x29: ffff80008001bae0 x28: 0000000000000000 x27: 0000000000000980
[    1.399741] x26: ffff00000158a080 x25: 0000000000000000 x24: ffff00003fdfb280
[    1.406885] x23: 0000000000000000 x22: 0000000000000000 x21: ffff000001d05980
[    1.414028] x20: ffff000001d05000 x19: ffff00000158a080 x18: 000000000000000a
[    1.421172] x17: 2034343161363264 x16: 6630303030303030 x15: 303a63616d5f7265
[    1.428316] x14: 68746f203043414d x13: 3962386136616339 x12: 00000000000000a1
[    1.435459] x11: ffff8000810f81a8 x10: ffff8000810f81a8 x9 : ffff80008001b718
[    1.442603] x8 : ffff80008001b720 x7 : ffff800081168210 x6 : 00000000ffffefff
[    1.449748] x5 : c0000000ffffefff x4 : 0000000000000000 x3 : 0000000000000000
[    1.456891] x2 : 0000000000000000 x1 : 0000000000000000 x0 : ffff00000152aac0
[    1.464035] Call trace:
[    1.466479]  mtk_add_mac+0x360/0x5a8 (P)
[    1.470405]  mtk_probe+0x9ac/0xea0
[    1.473810]  platform_probe+0x5c/0x90
[    1.477478]  really_probe+0x1c0/0x3a4
[    1.481144]  __driver_probe_device+0x134/0x14c
[    1.485591]  driver_probe_device+0x3c/0xf4
[    1.489690]  __driver_attach+0x190/0x1a0
[    1.493616]  bus_for_each_dev+0x84/0xdc
[    1.497455]  driver_attach+0x24/0x30
[    1.501033]  bus_add_driver+0x124/0x218
[    1.504872]  driver_register+0xbc/0xf8
[    1.508624]  __platform_driver_register+0x24/0x30
[    1.513334]  mtk_driver_init+0x1c/0x28
[    1.517088]  do_one_initcall+0x7c/0x1a0
[    1.520928]  do_initcalls+0x134/0x138
[    1.524595]  kernel_init_freeable+0x104/0x190
[    1.528955]  kernel_init+0x24/0x128
[    1.532448]  ret_from_fork+0x10/0x20
[    1.536032] Code: 2a1603e2 90003641 913a6021 97fd6bea (b94a0380)
[    1.542123] ---[ end trace 0000000000000000 ]---
[    1.548257] pstore: backend (ramoops) writing error (-28)
[    1.553683] Kernel panic - not syncing: Attempted to kill init! exitcode=0x0000000b
[    1.561340] SMP: stopping secondary CPUs
[    1.565267] Kernel Offset: disabled
[    1.568751] CPU features: 0x0000000,03000008,00040000,0400420b
[    1.574583] Memory Limit: none
[    1.579191] Rebooting in 30 seconds..