mt6625l: fix some kernel-ci warnings
cc1: error: arch/arm/mach-mt7623//dct/dct: No such file or directory [-Werror=missing-include-dirs]
>> cc1: error: drivers/misc/mediatek/connectivity/common/common_detect/../combo/linux/include: No such file or directory [-Werror=missing-include-dirs]
In file included from drivers/misc/mediatek/connectivity/common/common_detect/wmt_gpio.c:15:
drivers/misc/mediatek/connectivity/common/common_detect/wmt_gpio.h:24:10: fatal error: osal.h: No such file or directory
24 | #include "osal.h"
| ^~~~~~~~
cc1: all warnings being treated as errors
compilation terminated.
--
cc1: error: arch/arm/mach-mt7623//dct/dct: No such file or directory [-Werror=missing-include-dirs]
>> cc1: error: drivers/misc/mediatek/connectivity/common/common_detect/../combo/linux/include: No such file or directory [-Werror=missing-include-dirs]
cc1: all warnings being treated as errors

Kconfig warnings: (for reference only)
WARNING: unmet direct dependencies detected for MTK_GPS
Depends on ARM && GPS
Selected by
- MTK_GPS_SUPPORT && ARM

Reported-by: kernel test robot <lkp@intel.com>