DBG: try to set max-mtu when interface is xgmii (not working yet)
root@bpi-r4-v11:~
\# ip link set dev eth0 mtu 9000 up
Error: mtu greater than device maximum.
root@bpi-r4-v11:~
\# dmesg | grep eth
[    0.000000] psci: probing for conduit method from DT.
[    0.990468] mtk_soc_eth 15100000.ethernet: mtk_set_max_mtu: set max-mtu of mac #0 to 2022
[    0.998719] mtk_soc_eth 15100000.ethernet: generated random MAC address de:09:65:c8:ee:97
[    1.430246] mtk_soc_eth 15100000.ethernet: mtk_set_max_mtu: set max-mtu of mac #0 to 2022
[    1.438475] mtk_soc_eth 15100000.ethernet: generated random MAC address d2:3a:e9:9e:5f:e1
[    2.000310] mtk_soc_eth 15100000.ethernet: mtk_set_max_mtu: set max-mtu of mac #0 to 2022
[    2.009019] mtk_soc_eth 15100000.ethernet: generated random MAC address 52:28:cd:60:88:9e
[    2.022647] mtk_soc_eth 15100000.ethernet (unnamed net_device) (uninitialized): switched to inband/10e
[    2.038761] mtk_soc_eth 15100000.ethernet: mtk_set_max_mtu: set max-mtu of mac #1 to 2022
[    2.052416] mtk_soc_eth 15100000.ethernet: generated random MAC address ca:9c:39:60:d5:bb
[    2.063347] mtk_soc_eth 15100000.ethernet: mtk_set_max_mtu: set max-mtu of mac #2 to 2022
[    2.080236] mtk_soc_eth 15100000.ethernet eth0: mediatek frame engine at 0xffffffc084880000, irq 102
[    2.091090] mtk_soc_eth 15100000.ethernet eth1: mediatek frame engine at 0xffffffc084880000, irq 102
[    2.105703] mtk_soc_eth 15100000.ethernet eth2: mediatek frame engine at 0xffffffc084880000, irq 102
[    2.153297] mtk_soc_eth 15100000.ethernet eth0: entered promiscuous mode
root@bpi-r4-v11:~
\# ip link set dev eth0 up
[   87.074176] mtk_soc_eth 15100000.ethernet eth0: configuring for fixed/internal link mode
[   87.082306] mtk_soc_eth 15100000.ethernet: mtk_set_max_mtu: set max-mtu of mac #0 to 9190
[   87.090499] mtk_soc_eth 15100000.ethernet: mtk_set_max_mtu: set max-mtu of mac #0 to 9190
[   87.090523] mtk_soc_eth 15100000.ethernet eth0: Link is Up - 10Gbps/Full - flow control rx/tx
root@bpi-r4-v11:~
\#