i2c: mlxbf: Fix unused-variable warning
If CONFIG_ACPI is not set,
gcc warns about unused variable:

drivers/i2c/busses/i2c-mlxbf.c:2206:35: error: ‘mlxbf_i2c_chip’ defined but not used [-Werror=unused-variable]
 static struct mlxbf_i2c_chip_info mlxbf_i2c_chip[] = {
                                   ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Mark these variables as __maybe_unused  to fix this.

Fixes: b5b5b32081cd ("i2c: mlxbf: I2C SMBus driver for Mellanox BlueField SoC")
Signed-off-by: Ren Zhijie <renzhijie2@huawei.com>
Acked-by: Asmaa Mnebhi
Signed-off-by: Ren Zhijie <renzhijie2@huawei.com>
Signed-off-by: Wolfram Sang <wsa@kernel.org>