net: mediatek: add proprietary debugfs
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:355:5: warning: no previous prototype for 'mt798x_iomap' [-Wmissing-prototypes]
  355 | int mt798x_iomap(void)
      |     ^~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:375:5: warning: no previous prototype for 'mt798x_iounmap' [-Wmissing-prototypes]
  375 | int mt798x_iounmap(void)
      |     ^~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:384:6: warning: no previous prototype for 'mt7530_mdio_w32' [-Wmissing-prototypes]
  384 | void mt7530_mdio_w32(struct mtk_eth *eth, u16 reg, u32 val)
      |      ^~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:399:5: warning: no previous prototype for 'mt7530_mdio_r32' [-Wmissing-prototypes]
  399 | u32 mt7530_mdio_r32(struct mtk_eth *eth, u32 reg)
      |     ^~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:420:6: warning: no previous prototype for 'mtk_switch_w32' [-Wmissing-prototypes]
  420 | void mtk_switch_w32(struct mtk_eth *eth, u32 val, unsigned int reg)
      |      ^~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:426:5: warning: no previous prototype for 'mtk_switch_r32' [-Wmissing-prototypes]
  426 | u32 mtk_switch_r32(struct mtk_eth *eth, unsigned int reg)
      |     ^~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c: In function 'mtketh_debugfs_reset':
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:680:39: error: 'struct <anonymous>' has no member named 'force'
  680 |                 atomic_set(&eth->reset.force, 0);
      |                                       ^
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:683:44: error: 'struct <anonymous>' has no member named 'force'
  683 |                 if (atomic_read(&eth->reset.force))
      |                                            ^
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:689:39: error: 'struct <anonymous>' has no member named 'force'
  689 |                 atomic_set(&eth->reset.force, 1);
      |                                       ^
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c: At top level:
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:782:6: warning: no previous prototype for 'mii_mgr_read_combine' [-Wmissing-prototypes]
  782 | void mii_mgr_read_combine(struct mtk_eth *eth, u32 phy_addr, u32 phy_register,
      |      ^~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:792:6: warning: no previous prototype for 'mii_mgr_write_combine' [-Wmissing-prototypes]
  792 | void mii_mgr_write_combine(struct mtk_eth *eth, u16 phy_addr, u16 phy_register,
      |      ^~~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:991:6: warning: no previous prototype for 'dump_each_port' [-Wmissing-prototypes]
  991 | void dump_each_port(struct seq_file *seq, struct mtk_eth *eth, u32 base)
      |      ^~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c: In function 'dump_each_port':
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1003:33: warning: suggest braces around empty body in an 'else' statement [-Wempty-body]
 1003 |                                 ;
      |                                 ^
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c: At top level:
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1011:5: warning: no previous prototype for 'esw_cnt_read' [-Wmissing-prototypes]
 1011 | int esw_cnt_read(struct seq_file *seq, void *v)
      |     ^~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1085:6: warning: no previous prototype for 'xfi_mib_dump' [-Wmissing-prototypes]
 1085 | void xfi_mib_dump(struct seq_file *seq, u32 gdm_id)
      |      ^~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1111:5: warning: no previous prototype for 'xfi_cnt_read' [-Wmissing-prototypes]
 1111 | int xfi_cnt_read(struct seq_file *seq, void *v)
      |     ^~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1144:5: warning: no previous prototype for 'tx_ring_read' [-Wmissing-prototypes]
 1144 | int tx_ring_read(struct seq_file *seq, void *v)
      |     ^~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1190:5: warning: no previous prototype for 'hwtx_ring_read' [-Wmissing-prototypes]
 1190 | int hwtx_ring_read(struct seq_file *seq, void *v)
      |     ^~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1230:5: warning: no previous prototype for 'rx_ring_read' [-Wmissing-prototypes]
 1230 | int rx_ring_read(struct seq_file *seq, void *v)
      |     ^~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1282:5: warning: no previous prototype for 'dbg_regs_read' [-Wmissing-prototypes]
 1282 | int dbg_regs_read(struct seq_file *seq, void *v)
      |     ^~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1482:9: warning: no previous prototype for 'hw_lro_stats_write' [-Wmissing-prototypes]
 1482 | ssize_t hw_lro_stats_write(struct file *file, const char __user *buffer,
      |         ^~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1501:5: warning: no previous prototype for 'hw_lro_stats_read_v1' [-Wmissing-prototypes]
 1501 | int hw_lro_stats_read_v1(struct seq_file *seq, void *v)
      |     ^~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1598:5: warning: no previous prototype for 'hw_lro_stats_read_v2' [-Wmissing-prototypes]
 1598 | int hw_lro_stats_read_v2(struct seq_file *seq, void *v)
      |     ^~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1705:5: warning: no previous prototype for 'hw_lro_stats_read_wrapper' [-Wmissing-prototypes]
 1705 | int hw_lro_stats_read_wrapper(struct seq_file *seq, void *v)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1730:5: warning: no previous prototype for 'hwlro_agg_cnt_ctrl' [-Wmissing-prototypes]
 1730 | int hwlro_agg_cnt_ctrl(int cnt)
      |     ^~~~~~~~~~~~~~~~~~
In file included from /media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:29:
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c: In function 'hwlro_agg_cnt_ctrl':
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_soc.h:263:42: error: 'reg_map' undeclared (first use in this function); did you mean 'regmap'?
  263 | #define MTK_LRO_CTRL_DW2_CFG(x)         (reg_map->pdma.lro_ring_ctrl_dw1 + 0x4 + (x * 0x40))
      |                                          ^~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.h:118:37: note: in expansion of macro 'MTK_LRO_CTRL_DW2_CFG'
  118 |         u32 reg_val1 = mtk_r32(eth, MTK_LRO_CTRL_DW2_CFG(x));           \
      |                                     ^~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1736:17: note: in expansion of macro 'SET_PDMA_RXRING_MAX_AGG_CNT'
 1736 |                 SET_PDMA_RXRING_MAX_AGG_CNT(eth, i, cnt);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_soc.h:263:42: note: each undeclared identifier is reported only once for each function it appears in
  263 | #define MTK_LRO_CTRL_DW2_CFG(x)         (reg_map->pdma.lro_ring_ctrl_dw1 + 0x4 + (x * 0x40))
      |                                          ^~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.h:118:37: note: in expansion of macro 'MTK_LRO_CTRL_DW2_CFG'
  118 |         u32 reg_val1 = mtk_r32(eth, MTK_LRO_CTRL_DW2_CFG(x));           \
      |                                     ^~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1736:17: note: in expansion of macro 'SET_PDMA_RXRING_MAX_AGG_CNT'
 1736 |                 SET_PDMA_RXRING_MAX_AGG_CNT(eth, i, cnt);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c: At top level:
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1741:5: warning: no previous prototype for 'hwlro_agg_time_ctrl' [-Wmissing-prototypes]
 1741 | int hwlro_agg_time_ctrl(int time)
      |     ^~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c: In function 'hwlro_agg_time_ctrl':
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_soc.h:263:42: error: 'reg_map' undeclared (first use in this function); did you mean 'regmap'?
  263 | #define MTK_LRO_CTRL_DW2_CFG(x)         (reg_map->pdma.lro_ring_ctrl_dw1 + 0x4 + (x * 0x40))
      |                                          ^~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.h:131:36: note: in expansion of macro 'MTK_LRO_CTRL_DW2_CFG'
  131 |         u32 reg_val = mtk_r32(eth, MTK_LRO_CTRL_DW2_CFG(x));            \
      |                                    ^~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1747:17: note: in expansion of macro 'SET_PDMA_RXRING_AGG_TIME'
 1747 |                 SET_PDMA_RXRING_AGG_TIME(eth, i, time);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c: At top level:
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1752:5: warning: no previous prototype for 'hwlro_age_time_ctrl' [-Wmissing-prototypes]
 1752 | int hwlro_age_time_ctrl(int time)
      |     ^~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c: In function 'hwlro_age_time_ctrl':
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_soc.h:262:42: error: 'reg_map' undeclared (first use in this function); did you mean 'regmap'?
  262 | #define MTK_LRO_CTRL_DW1_CFG(x)         (reg_map->pdma.lro_ring_ctrl_dw1 + (x * 0x40))
      |                                          ^~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.h:139:37: note: in expansion of macro 'MTK_LRO_CTRL_DW1_CFG'
  139 |         u32 reg_val1 = mtk_r32(eth, MTK_LRO_CTRL_DW1_CFG(x));           \
      |                                     ^~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1758:17: note: in expansion of macro 'SET_PDMA_RXRING_AGE_TIME'
 1758 |                 SET_PDMA_RXRING_AGE_TIME(eth, i, time);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c: At top level:
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1762:5: warning: no previous prototype for 'hwlro_threshold_ctrl' [-Wmissing-prototypes]
 1762 | int hwlro_threshold_ctrl(int bandwidth)
      |     ^~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1771:5: warning: no previous prototype for 'hwlro_ring_enable_ctrl' [-Wmissing-prototypes]
 1771 | int hwlro_ring_enable_ctrl(int enable)
      |     ^~~~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c: In function 'hwlro_ring_enable_ctrl':
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_soc.h:263:42: error: 'reg_map' undeclared (first use in this function); did you mean 'regmap'?
  263 | #define MTK_LRO_CTRL_DW2_CFG(x)         (reg_map->pdma.lro_ring_ctrl_dw1 + 0x4 + (x * 0x40))
      |                                          ^~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.h:159:36: note: in expansion of macro 'MTK_LRO_CTRL_DW2_CFG'
  159 |         u32 reg_val = mtk_r32(eth, MTK_LRO_CTRL_DW2_CFG(x));            \
      |                                    ^~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1779:17: note: in expansion of macro 'SET_PDMA_RXRING_VALID'
 1779 |                 SET_PDMA_RXRING_VALID(eth, i, enable);
      |                 ^~~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c: At top level:
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1784:5: warning: no previous prototype for 'hwlro_stats_enable_ctrl' [-Wmissing-prototypes]
 1784 | int hwlro_stats_enable_ctrl(int enable)
      |     ^~~~~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1801:9: warning: no previous prototype for 'hw_lro_auto_tlb_write' [-Wmissing-prototypes]
 1801 | ssize_t hw_lro_auto_tlb_write(struct file *file, const char __user *buffer,
      |         ^~~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1839:6: warning: no previous prototype for 'hw_lro_auto_tlb_dump_v1' [-Wmissing-prototypes]
 1839 | void hw_lro_auto_tlb_dump_v1(struct seq_file *seq, u32 index)
      |      ^~~~~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1898:6: warning: no previous prototype for 'hw_lro_auto_tlb_dump_v2' [-Wmissing-prototypes]
 1898 | void hw_lro_auto_tlb_dump_v2(struct seq_file *seq, u32 index)
      |      ^~~~~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1969:5: warning: no previous prototype for 'hw_lro_auto_tlb_read' [-Wmissing-prototypes]
 1969 | int hw_lro_auto_tlb_read(struct seq_file *seq, void *v)
      |     ^~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c: In function 'hw_lro_auto_tlb_read':
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_soc.h:262:42: error: 'reg_map' undeclared (first use in this function); did you mean 'regmap'?
  262 | #define MTK_LRO_CTRL_DW1_CFG(x)         (reg_map->pdma.lro_ring_ctrl_dw1 + (x * 0x40))
      |                                          ^~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:2009:40: note: in expansion of macro 'MTK_LRO_CTRL_DW1_CFG'
 2009 |                 reg_op1 = mtk_r32(eth, MTK_LRO_CTRL_DW1_CFG(i));
      |                                        ^~~~~~~~~~~~~~~~~~~~
make[7]: *** [/media/data_ext/git/kernel/BPI-R2-4.14/scripts/Makefile.build:194: drivers/net/ethernet/mediatek/mtk_eth_dbg.o] Error 1
make[7]: *** Waiting for unfinished jobs....
make[6]: *** [/media/data_ext/git/kernel/BPI-R2-4.14/scripts/Makefile.build:440: drivers/net/ethernet/mediatek] Error 2
make[5]: *** [/media/data_ext/git/kernel/BPI-R2-4.14/scripts/Makefile.build:440: drivers/net/ethernet] Error 2
make[1]: Leaving directory '/media/data_ext/git/kernel/build'

fix build-errors/warnings for mtk_eth_dbg

these are still there:

In file included from drivers/net/ethernet/mediatek/mtk_eth_dbg.c:29:
drivers/net/ethernet/mediatek/mtk_eth_dbg.c: In function 'hwlro_threshold_ctrl':
drivers/net/ethernet/mediatek/mtk_eth_soc.h:204:34: error: 'reg_map' undeclared (first use in this function); did you mean 'regmap'?
  204 | #define MTK_PDMA_LRO_CTRL_DW2   (reg_map->pdma.lro_ctrl_dw0 + 0x08)
      |                                  ^~~~~~~
drivers/net/ethernet/mediatek/mtk_eth_dbg.h:152:36: note: in expansion of macro 'MTK_PDMA_LRO_CTRL_DW2'
  152 |         u32 reg_val = mtk_r32(eth, MTK_PDMA_LRO_CTRL_DW2);              \
      |                                    ^~~~~~~~~~~~~~~~~~~~~
drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1769:9: note: in expansion of macro 'SET_PDMA_LRO_BW_THRESHOLD'
 1769 |         SET_PDMA_LRO_BW_THRESHOLD(eth, bandwidth);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
drivers/net/ethernet/mediatek/mtk_eth_soc.h:204:34: note: each undeclared identifier is reported only once for each function it appears in
  204 | #define MTK_PDMA_LRO_CTRL_DW2   (reg_map->pdma.lro_ctrl_dw0 + 0x08)
      |                                  ^~~~~~~
drivers/net/ethernet/mediatek/mtk_eth_dbg.h:152:36: note: in expansion of macro 'MTK_PDMA_LRO_CTRL_DW2'
  152 |         u32 reg_val = mtk_r32(eth, MTK_PDMA_LRO_CTRL_DW2);              \
      |                                    ^~~~~~~~~~~~~~~~~~~~~
drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1769:9: note: in expansion of macro 'SET_PDMA_LRO_BW_THRESHOLD'
 1769 |         SET_PDMA_LRO_BW_THRESHOLD(eth, bandwidth);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
drivers/net/ethernet/mediatek/mtk_eth_dbg.c: In function 'hw_lro_auto_tlb_dump_v1':
drivers/net/ethernet/mediatek/mtk_eth_soc.h:202:34: error: 'reg_map' undeclared (first use in this function); did you mean 'regmap'?
  202 | #define MTK_PDMA_LRO_CTRL_DW0   (reg_map->pdma.lro_ctrl_dw0)
      |                                  ^~~~~~~
drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1868:26: note: in expansion of macro 'MTK_PDMA_LRO_CTRL_DW0'
 1868 |         if (mtk_r32(eth, MTK_PDMA_LRO_CTRL_DW0) & MTK_LRO_ALT_PKT_CNT_MODE)
      |                          ^~~~~~~~~~~~~~~~~~~~~
drivers/net/ethernet/mediatek/mtk_eth_dbg.c: In function 'hw_lro_auto_tlb_dump_v2':
drivers/net/ethernet/mediatek/mtk_eth_soc.h:202:34: error: 'reg_map' undeclared (first use in this function); did you mean 'regmap'?
  202 | #define MTK_PDMA_LRO_CTRL_DW0   (reg_map->pdma.lro_ctrl_dw0)
      |                                  ^~~~~~~
drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1919:26: note: in expansion of macro 'MTK_PDMA_LRO_CTRL_DW0'
 1919 |         if (mtk_r32(eth, MTK_PDMA_LRO_CTRL_DW0) & MTK_LRO_ALT_PKT_CNT_MODE)
      |                          ^~~~~~~~~~~~~~~~~~~~~

more fixes for mtk_eth_dbg after adding lro code

net: mediatek: update propritary debugfs

net: mediatek: add some missing values